name: Publish to all the places
on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        loader: [ quilt, forge, fabric ]
    runs-on: ubuntu-latest
    steps:
      - name: Echo env
        run: env
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Prep wrapper
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: cd ${{ matrix.loader }} && ../gradlew clean build
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 843552
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: MpNGsSsC
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "[${{ matrix.loader }} ${{ github.ref_name }}]"
          github-token: "${{secrets.GH_TOKEN}}"

          version-type: release
          version-resolver: exact

          files-primary: "${{ matrix.loader }}/build/libs/!(*-@(dev|dev-shadow|sources|javadoc)).jar"

          loaders: ${{ matrix.loader }}

